SUCCESS = 1
FAILURE = -1

# ACTION RESULT
ACTION_RESULT_NONE = 0x00
ACTION_RESULT_ACTIVITY_CHANGE = 0x01
ACTION_RESULT_KEYBOARD_UP = 0x02
ACTION_RESULT_KEYBOARD_DOWN = 0x04
ACTION_RESULT_SCREEN_CHANGE = 0x08
ACTION_RESULT_UNKNOWN = 0x10
ACTION_RESULT_DIALOG_SHOWN = 0x20
ACTION_RESULT_DIALOG_HIDDEN = 0x40
ACTION_RESULT_OUTSIDE_APP = 0x80

# ACTIVITY CONSTANTS
ACTIVITY_DONT_CARE = 'DONT_CARE'
ACTIVITY_ROOT = 'ROOT'

# ACTION types for traverserdb Type column in Actions table
ACTION_VERIFY_TEXT = 'VerifyText'
ACTION_WAIT_TEXT = 'WaitText'
ACTION_WAIT_OBJECT = 'WaitObject'
ACTION_SELECT_FROM_LIST = 'SelectFromList'
ACTION_TAP_COORDINATE = 'TapCoordinate'
ACTION_TAP_DOWN_COORDINATE = 'TapDownCoordinate'
ACTION_TAP_UP_COORDINATE = 'TapUpCoordinate'
ACTION_LONG_TAP_COORDINATE = 'LongTapCoordinate'
ACTION_MOVE_TO_COORDINATE = 'MoveToCoordinate'
ACTION_TAP_OBJECT = 'TapObject'
ACTION_TAP_DOWN_OBJECT = 'TapDownObject'
ACTION_TAP_UP_OBJECT = 'TapUpObject'
ACTION_LONG_TAP_OBJECT = 'LongTapObject'
ACTION_MOVE_TO_OBJECT = 'MoveToObject'
ACTION_DRAG = 'Drag'
ACTION_TOUCH_SCROLL = 'TouchScroll'
ACTION_MOVE_TRACK_BALL = 'MoveTrackBall'
ACTION_SELECT_FROM_MENU = 'SelectFromMenu'
ACTION_IS_TRUE = 'IsTrue'
ACTION_SET_TARGET = 'SetTarget'
ACTION_UPDATE_SCREEN = 'UpdateScreen'
ACTION_DELAY = 'Delay'
ACTION_TYPE = 'Type'
ACTION_PRESS_KEY = 'PressKey'
ACTION_PRESS_HARD_KEY = 'PressHardKey'
ACTION_PRESS_KEY_UP = 'PressKeyUp'
ACTION_PRESS_KEY_DOWN = 'PressKeyDown'
ACTION_LONG_PRESS_KEY = 'LongPressKey'
ACTION_CHECK_PROPERTY = 'CheckProperty'
ACTION_LAUNCH_APP = 'LaunchApp'
ACTION_OBJECT_VISIBLE = 'ObjectVisible'
ACTION_EMULATOR_KEYWORD = 'EmulatorKeyword'
ACTION_SET_NETWORK_DELAY = 'SetNetworkDelay'
ACTION_SET_NETWORK_SPEED = 'SetNetworkSpeed'
ACTION_SEND_SMS = 'SendSMS'
ACTION_TAKE_SCREENSHOT = 'TakeScreenshot'

# GraphViz Node Image Size
NODE_WIDTH = 64
NODE_HEIGHT = 64

# Component Paradigms
COMPONENT_UNKNOWN = 1
COMPONENT_LOGIN = 2
COMPONENT_SHARE_APP = 4
COMPONENT_RATE_APP = 8
COMPONENT_OPEN_WITH = 16
COMPONENT_NEGATIVE_RESPONSE = 32

#